version: '2'
services:
    neo4j3:
        environment:
            NEO4J_AUTH: "neo4j/123456"
        image: neo4j:4.3.1
        ports:
            - "27474:7474"
            - "27687:7687"
        container_name: neo4j3
        volumes:
            - d:/docker_volume/neo4j2/data:/data
            - d:/docker_volume/neo4j2/logs:/logs
            - d:/docker_volume/neo4j2/import:/var/lib/neo4j/import
            - d:/docker_volume/neo4j2/plugins:/plugins
            - d:/docker_volume/neo4j2/upload:/upload